baseurl: ""
url: "https://vjstv.com"
permalink: "/:title"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives

collections:
  vjs:
    output: true
    permalink: /artists/:name
  projects:
    output: true
    permalink: /projects/:name
  events:
    output: true
    permalink: /events/:name
  studios:
    output: true
    permalink: /studios/:name
  technology:
    output: true
    permalink: /technology/:name
  sponsors:
    output: true
    permalink: /sponsors/:name

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
pagination:
  enabled: false

############################################################

# Jekyll Archives Configuration
jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: tag
    category: category
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'

feed:
  collections:
    posts:
      path: "/index.xml"

highlighter: rouge
