baseurl: ""
url: "https://vjstv.com"
permalink: "/:title"

include:
  - _routes.json
  - _headers

plugins:
  - jekyll-feed

collections:
  vjs:
    output: true
    permalink: /artists/:name
  projects:
    output: true
    permalink: /projects/:name
  events:
    output: true
    permalink: /events/:name
  studios:
    output: true
    permalink: /studios/:name
  technology:
    output: true
    permalink: /technology/:name
  sponsors:
    output: true
    permalink: /sponsors/:name
  loop_packs:
    output: true
    permalink: /marketplace/:name

future: true
highlighter: rouge

exclude:
  - .local
  - .replit
  - attached_assets
  - portfolios
  - _portfolio
  - blogs
  - _posts
  - _authors
  - _shop_items
  - shop
  - services
  - about
  - contact
  - features
  - elements
  - home-pages
  - search.json
  - CNAME
  - cloudflare.toml
  - github.toml
  - netlify.toml
  - README.md
  - Gemfile
  - Gemfile.lock
  - replit.md
  - node_modules
  - vendor
  - functions
  - api
  - _site
  - wrangler.jsonc
  - wrangler.json
  - .gitignore
