name = "website"
main = "src/index.js"
compatibility_date = "2026-03-19"

routes = [
  { pattern = "vjstv.com/*", zone_name = "vjstv.com" },
  { pattern = "*.vjstv.com/*", zone_name = "vjstv.com" }
]

[build]
command = "jekyll build"
cwd = "./"
watch_paths = ["_config.yml", "_includes/**/*", "_layouts/**/*", "_data/**/*", "_vjs/**/*", "_site/**/*"]

[env.production]
routes = [
  { pattern = "vjstv.com/*", zone_name = "vjstv.com" },
  { pattern = "*.vjstv.com/*", zone_name = "vjstv.com" }
]

[env.production.build]
command = "jekyll build"

vars = { JEKYLL_ENV = "production" }
