uploads = []
outputs = []

[[generated]]
id = "FXUPChsOeyoL0PhadxH7H"
uri = "file://assets/images/loop-packs/vjstv-loops-01.png"
type = "image"
title = "generated_image"

[[generated]]
id = "k8NjSOsu8vMRkbZv-CICw"
uri = "file://assets/images/loop-packs/vjstv-loops-01/preview-01.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yPHhbHvDUTXOoycBbo6_S"
uri = "file://assets/images/loop-packs/vjstv-loops-01/preview-02.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PLIIved1rJcYxo1zkwGkW"
uri = "file://assets/images/loop-packs/vjstv-loops-01/preview-03.png"
type = "image"
title = "generated_image"

[[generated]]
id = "s7W8tjyr_ubrM3f1Y9hYc"
uri = "file://assets/images/loop-packs/vjstv-loops-01/preview-04.png"
type = "image"
title = "generated_image"
